@startuml
autonumber

==  服务启动过程 ==

P_A -> P_A: 在指定端口启动 Netty 服务
note right: 读取配置文件信息获取启动端口

P_A -> 注册中心 : 向 注册中心 注册服务 AServiceImpl
note right: 服务名称为:

==  等待消费者发送 RPC 请求 ==


C_B -> C_B: 查询本地缓存中服务A的信息

alt 本地没有服务A的地址信息
C_B -> 注册中心: 获取指定服务提供者的地址
note left: 服务不存在则抛出异常
end



C_B -> C_B: 序列化请求数据
C_B -[#0000FF]> P_A: 根据注册中心返回的地址和端口调用指定方法
P_A -> P_A: 实现反序列化请求数据
P_A --[#0000FF]--> C_B: 返回相应数据
C_B -> C_B: 反序列化相应数据











@enduml
